// components/ProjectCard.vue
<template>
  <div class="bg-gray-900/50 rounded-lg overflow-hidden h-full flex flex-col">
    <div class="h-48 bg-gray-800/50 relative overflow-hidden group">
      <img 
        :src="project.image" 
        :alt="project.title" 
        class="w-full h-full object-cover object-center transition-transform duration-500 group-hover:scale-110"
      />
      <!-- Add colorful overlay gradient -->
      <div class="absolute inset-0 bg-gradient-to-br from-primary/40 to-secondary/40 mix-blend-overlay"></div>
    </div>
    <div class="p-6 flex flex-col flex-grow">
      <h3 class="text-xl font-semibold text-white mb-2">{{ project.title }}</h3>
      <p class="text-gray-400 mb-4 flex-grow">
        {{ project.description }}
      </p>
      <div class="flex flex-wrap gap-2 mb-4">
        <span 
          v-for="tag in project.tags" 
          :key="tag"
          class="text-xs px-2 py-1 bg-primary/20 text-primary rounded"
        >
          {{ tag }}
        </span>
      </div>
      <div class="flex gap-4 mt-auto">
        <a 
          :href="project.sourceUrl" 
          target="_blank" 
          rel="noopener noreferrer" 
          class="text-primary hover:text-primary/80 text-sm font-medium"
        >
          Source Code
        </a>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  project: {
    id: string
    title: string
    description: string
    image: string
    tags: string[]
    sourceUrl: string
  }
}>()
</script>

// src/components/projects/ProjectCard.tsx
import Image from "next/image"
import { ExternalLink } from "lucide-react"

interface ProjectProps {
  project: {
    id: string
    title: string
    description: string
    image: string
    tags: string[]
    sourceUrl: string
  }
}

export function ProjectCard({ project }: ProjectProps) {
  return (
    <div className="bg-card rounded-lg overflow-hidden h-full flex flex-col border border-border/50 hover:border-border transition-colors">
      <div className="h-48 relative overflow-hidden group bg-muted">
        <Image
          src={project.image}
          alt={project.title}
          fill
          className="object-cover transition-transform duration-500 group-hover:scale-110"
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
        {/* Add colorful overlay gradient */}
        <div className="absolute inset-0 bg-gradient-to-br from-accent/40 to-secondary/40 mix-blend-overlay pointer-events-none" />
      </div>
      <div className="p-6 flex flex-col flex-grow">
        <h3 className="text-xl font-semibold text-foreground mb-2">{project.title}</h3>
        <p className="text-muted-foreground mb-4 flex-grow text-sm leading-relaxed">
          {project.description}
        </p>
        <div className="flex flex-wrap gap-2 mb-6">
          {project.tags.map((tag) => (
            <span
              key={tag}
              className="text-xs px-2.5 py-1 bg-accent/10 text-accent font-medium rounded-full"
            >
              {tag}
            </span>
          ))}
        </div>
        <div className="flex gap-4 mt-auto">
          <a
            href={project.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:text-primary/80 text-sm font-medium flex items-center gap-1 transition-colors group"
          >
            Source Code
            <ExternalLink className="w-3.5 h-3.5 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
          </a>
        </div>
      </div>
    </div>
  )
}
