// src/components/home/HeroSection.tsx
"use client"

import React, { useState, useEffect } from "react"
import { socialLinks } from "@/lib/site-data"
import { ArrowUpRight, ChevronDown } from "lucide-react"
import { cn } from "@/lib/utils"
import Link from "next/link"

export function HeroSection() {
  const [scrolledDown, setScrolledDown] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      setScrolledDown(window.scrollY > 100)
    }
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  return (
    <section
      className="relative overflow-hidden flex flex-col items-center justify-start pt-[calc(env(safe-area-inset-top)+clamp(4.25rem,8.5svh,6rem))] md:pt-16 lg:pt-20 pb-[clamp(1rem,4svh,3.5rem)] md:pb-0"
      style={{ background: "var(--neu-surface)" }}
    >

      {/* Hero Title — vertically centered in the gap between header bar and cards */}
      <div className="w-full max-w-5xl mx-auto px-6 sm:px-6 text-center flex items-center justify-center h-[clamp(7rem,18svh,9.75rem)] sm:h-[clamp(8rem,20svh,11rem)] md:h-[16rem] lg:h-[18rem] xl:h-[20rem]">
        <h1
          className="font-serif max-md:font-extrabold font-bold md:font-semibold text-[1.625rem] sm:text-[2.35rem] md:text-[3.125rem] lg:text-[3.75rem] xl:text-[4.25rem] leading-[1.1] md:whitespace-nowrap inline-block px-4 -mx-4 pb-2.5 max-md:subpixel-antialiased max-md:[-webkit-text-stroke:0.6px_transparent]"
          style={{
            background: "linear-gradient(to bottom, var(--hero-gradient-top) 0%, var(--hero-gradient-top) var(--hero-gradient-stop, 30%), var(--hero-gradient-bottom) 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
          }}
        >
          <span className="block">AI-powered mobile apps.</span>
          <span className="block">Designed with precision.</span>
        </h1>
      </div>

      {/* Mobile Design: Parent Neumorphic Container (Visible only on small screens) */}
      <div className="w-full max-w-md mx-auto px-6 mb-[clamp(1.25rem,4.5svh,3rem)] md:hidden">
        <div className="neu-container overflow-hidden pt-3">
          {/* Top: Raised All Projects rectangle */}
          <div className="px-3">
            <Link
              href="/projects"
              className="group relative block rounded-[32px] h-[clamp(7.25rem,19svh,10rem)] overflow-hidden neu-raised neu-mobile-neumorphic transform-gpu p-1"
            >
              {/* Lava lamp effect background */}
              <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none animate-color-shift">
                <div className="absolute inset-0 bg-[var(--neu-surface)]" />
                <div className="absolute inset-0 overflow-hidden pointer-events-none" style={{ maskImage: 'radial-gradient(ellipse at center, black 25%, transparent 75%)', WebkitMaskImage: 'radial-gradient(ellipse at center, black 25%, transparent 75%)' }}>
                  <div className="absolute top-[10%] left-[5%] w-[50%] h-[50%] rounded-full bg-blue-500/40 animate-lava [--drift-name:drift-wide] [--drift-duration:12s] [--morph-name:morph] [--morph-duration:10s] [--glow-blur:80px] scale-125" style={{ filter: 'blur(var(--glow-blur))' }} />
                  <div className="absolute bottom-[5%] right-[5%] w-[45%] h-[45%] rounded-full bg-purple-500/40 animate-lava [--drift-name:drift-wide] [--drift-duration:15s] [--morph-name:morph-alt] [--morph-duration:13s] [--drift-delay:1s] [--glow-blur:75px] scale-110" style={{ filter: 'blur(var(--glow-blur))' }} />
                  <div className="absolute top-[30%] left-[30%] w-[30%] h-[30%] rounded-full bg-white/50 animate-lava [--drift-name:drift-wide] [--drift-duration:14s] [--morph-name:morph] [--morph-duration:18s] [--glow-blur:50px] scale-140" style={{ filter: 'blur(var(--glow-blur))' }} />
                </div>
              </div>
              
              <div className="relative z-10 h-full flex flex-col items-center justify-center text-center">
                <div className="flex items-center gap-2">
                  <span className="text-[1.125rem] font-semibold text-zinc-900 dark:text-white">View All Projects</span>
                  <ArrowUpRight className="w-5 h-5 text-zinc-900 dark:text-white" />
                </div>
              </div>
            </Link>
          </div>
          
          <div className="h-3 relative">
            <div className="absolute top-0 bottom-0 left-1/2 w-[1px] -translate-x-1/2 border-r neu-separator" />
          </div>

          {/* Middle: Flat Grid of Categories (responsive row height) */}
          <div className="grid grid-cols-2">
            <Link href="/apps" className="flex items-center h-[clamp(5.25rem,11svh,5.75rem)] border-r border-b neu-separator text-zinc-900 dark:text-zinc-100 font-medium text-[0.95rem] active:bg-zinc-100/10 transition-colors">
              <div className="w-1/2 flex justify-center">
                <div className="w-8 text-left whitespace-nowrap">Mobile Apps</div>
              </div>
            </Link>
            <Link href="/ai" className="flex items-center h-[clamp(5.25rem,11svh,5.75rem)] border-b neu-separator text-zinc-900 dark:text-zinc-100 font-medium text-[0.95rem] active:bg-zinc-100/10 transition-colors">
              <div className="w-1/2 flex justify-center">
                <div className="w-8 text-left whitespace-nowrap">AI Engineering</div>
              </div>
            </Link>
            <Link href="/design" className="flex items-center h-[clamp(5.25rem,11svh,5.75rem)] border-r border-b neu-separator text-zinc-900 dark:text-zinc-100 font-medium text-[0.95rem] active:bg-zinc-100/10 transition-colors">
              <div className="w-1/2 flex justify-center">
                <div className="w-8 text-left whitespace-nowrap">Design</div>
              </div>
            </Link>
            <a href={socialLinks.resume} download={socialLinks.resumeDownloadName} className="flex items-center h-[clamp(5.25rem,11svh,5.75rem)] border-b neu-separator text-zinc-900 dark:text-zinc-100 font-medium text-[0.95rem] active:bg-zinc-100/10 transition-colors">
              <div className="w-1/2 flex justify-center">
                <div className="w-8 text-left whitespace-nowrap">Resume</div>
              </div>
            </a>
          </div>

          {/* Bottom: Social Icons Row (responsive row height) */}
          <div className="grid grid-cols-4">
            <a href={socialLinks.email} className="flex items-center justify-center h-[clamp(5.25rem,11svh,5.75rem)] border-r neu-separator group active:bg-zinc-100/10 transition-colors">
              <div className="w-12 h-12 rounded-full flex items-center justify-center transition-colors text-zinc-500 dark:text-zinc-400 group-hover:text-zinc-900 dark:group-hover:text-zinc-100">
                <svg viewBox="0 0 24 24" className="w-8 h-8 fill-current" xmlns="http://www.w3.org/2000/svg">
                  <path d="M20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-0.4 4.25l-7.07 4.42c-0.32 0.2-0.74 0.2-1.06 0L4.4 8.25c-0.25-0.16-0.4-0.43-0.4-0.72 0-0.67 0.73-1.07 1.27-0.67L12 11l6.73-4.14c0.54-0.4 1.27 0 1.27 0.67 0 0.29-0.15 0.56-0.4 0.72z" />
                </svg>
              </div>
            </a>
            <a href="#contact" className="flex items-center justify-center h-[clamp(5.25rem,11svh,5.75rem)] border-r neu-separator group active:bg-zinc-100/10 transition-colors">
              <div className="w-12 h-12 rounded-full flex items-center justify-center transition-colors text-zinc-500 dark:text-zinc-400 group-hover:text-zinc-900 dark:group-hover:text-zinc-100">
                <svg viewBox="0 0 24 24" className="w-8 h-8 fill-current" xmlns="http://www.w3.org/2000/svg">
                  <path d="M16.969 16.927a2.561 2.561 0 0 0 1.901.677 2.501 2.501 0 0 0 1.531-.475c.362-.235.636-.584.779-.99h2.585a5.091 5.091 0 0 1-1.9 2.896 5.292 5.292 0 0 1-3.091.88 5.839 5.839 0 0 1-2.284-.433 4.871 4.871 0 0 1-1.723-1.211 5.657 5.657 0 0 1-1.08-1.874 7.057 7.057 0 0 1-.383-2.393c-.005-.8.129-1.595.396-2.349a5.313 5.313 0 0 1 5.088-3.604 4.87 4.87 0 0 1 2.376.563c.661.362 1.231.87 1.668 1.485a6.2 6.2 0 0 1 .943 2.133c.194.821.263 1.666.205 2.508h-7.699c-.063.79.184 1.574.688 2.187ZM6.947 4.084a8.065 8.065 0 0 1 1.928.198 4.29 4.29 0 0 1 1.49.638c.418.303.748.711.958 1.182.241.579.357 1.203.341 1.83a3.506 3.506 0 0 1-.506 1.961 3.726 3.726 0 0 1-1.503 1.287 3.588 3.588 0 0 1 2.027 1.437c.464.747.697 1.615.67 2.494a4.593 4.593 0 0 1-.423 2.032 3.945 3.945 0 0 1-1.163 1.413 5.114 5.114 0 0 1-1.683.807 7.135 7.135 0 0 1-1.928.259H0V4.084h6.947Zm-.235 12.9c.308.004.616-.029.916-.099a2.18 2.18 0 0 0 .766-.332c.228-.158.411-.371.534-.619.142-.317.208-.663.191-1.009a2.08 2.08 0 0 0-.642-1.715 2.618 2.618 0 0 0-1.696-.505h-3.54v4.279h3.471Zm13.635-5.967a2.13 2.13 0 0 0-1.654-.619 2.336 2.336 0 0 0-1.163.259 2.474 2.474 0 0 0-.738.62 2.359 2.359 0 0 0-.396.792c-.074.239-.12.485-.137.734h4.769a3.239 3.239 0 0 0-.679-1.785l-.002-.001Zm-13.813-.648a2.254 2.254 0 0 0 1.423-.433c.399-.355.607-.88.56-1.413a1.916 1.916 0 0 0-.178-.891 1.298 1.298 0 0 0-.495-.533 1.851 1.851 0 0 0-.711-.274 3.966 3.966 0 0 0-.835-.073H3.241v3.631h3.293v-.014ZM21.62 5.122h-5.976v1.527h5.976V5.122Z" />
                </svg>
              </div>
            </a>
            <a href={socialLinks.linkedin} target="_blank" rel="noopener noreferrer" className="flex items-center justify-center h-[clamp(5.25rem,11svh,5.75rem)] border-r neu-separator group active:bg-zinc-100/10 transition-colors">
              <div className="w-12 h-12 rounded-full flex items-center justify-center transition-colors text-zinc-500 dark:text-zinc-400 group-hover:text-zinc-900 dark:group-hover:text-zinc-100">
                <svg viewBox="0 0 24 24" className="w-8 h-8 fill-current" xmlns="http://www.w3.org/2000/svg">
                  <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                </svg>
              </div>
            </a>
            <a href={socialLinks.github} target="_blank" rel="noopener noreferrer" className="flex items-center justify-center h-[clamp(5.25rem,11svh,5.75rem)] group active:bg-zinc-100/10 transition-colors">
              <div className="w-12 h-12 rounded-full flex items-center justify-center transition-colors text-zinc-500 dark:text-zinc-400 group-hover:text-zinc-900 dark:group-hover:text-zinc-100">
                <svg viewBox="0 0 24 24" className="w-8 h-8 fill-current" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                </svg>
              </div>
            </a>
          </div>
        </div>
      </div>

      {/* Desktop/Bigger screens Design: (Hidden on mobile) */}
      <div className="hidden md:block w-full max-w-5xl mx-auto px-6 sm:px-6">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-x-4 gap-y-4 md:gap-5">
          {/* Accent-fill service cards: Mobile Apps, AI, Design */}
          {([
            { 
              href: "/apps", 
              label: "Mobile Apps", 
              accent: "iOS · Android · React Native",
              orderClass: "order-2 md:order-1",
            },
            { 
              href: "/ai", 
              label: "AI Engineering", 
              accent: "ML · LLMs · Intelligent Systems",
              orderClass: "order-3 md:order-2",
            },
            { 
              href: "/design", 
              label: "Design", 
              accent: "Prototyping · Design Systems",
              orderClass: "order-4 md:order-3",
            },
          ]).map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className={cn(
                "group relative rounded-3xl overflow-hidden aspect-[2.15/1] md:aspect-auto h-auto md:h-36 lg:h-40",
                "neu-raised neu-raised-accent transition-all duration-500 ease-in-out",
                item.orderClass
              )}
            >
                <div className="absolute inset-4 md:inset-5 z-10 pointer-events-none">
                  <ArrowUpRight 
                    className="md:hidden absolute top-0 right-0 w-4 h-4 transition-colors opacity-70 group-hover:opacity-100 text-zinc-500 dark:text-zinc-400" 
                  />
                  <div className="absolute bottom-0 md:bottom-0 left-1.5 md:left-0">
                    <span 
                      className="text-sm sm:text-base font-semibold block text-zinc-900 dark:text-zinc-50"
                    >
                      {item.label}
                    </span>
                    <span 
                      className="hidden md:block text-xs text-zinc-800/70 dark:text-zinc-400/70 group-hover:text-zinc-800/90 dark:group-hover:text-zinc-400/90 transition-colors mt-1"
                    >
                      {item.accent}
                    </span>
                  </div>
                </div>
              </Link>
          ))}

          {/* All Projects — like other 3 rectangles with light gray background */}
          <Link
            href="/projects"
            className={cn(
              "group relative rounded-3xl overflow-hidden h-32 md:h-full col-span-2 md:col-span-1 md:row-span-2 order-1 md:order-4",
              "neu-raised neu-raised-accent neu-mobile-neumorphic transform-gpu mb-2 md:mb-0"
            )}
          >
            {/* 1. Underlying Dreamy Glow Layer - No hard edges */}
            <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none animate-color-shift">
              <div className="absolute inset-0 bg-[var(--neu-surface)] transition-colors duration-500" />
              <div 
                className="dark:hidden absolute inset-0 overflow-hidden pointer-events-none"
                style={{
                  maskImage: 'radial-gradient(ellipse at center, black 25%, transparent 75%)',
                  WebkitMaskImage: 'radial-gradient(ellipse at center, black 25%, transparent 75%)'
                }}
              >
                <div className="absolute top-[10%] left-[5%] w-[50%] h-[50%] rounded-full bg-blue-500/40 animate-lava [--drift-name:drift-wide] [--drift-duration:12s] [--morph-name:morph] [--morph-duration:10s] [--color-duration:18s] [--glow-blur:80px] scale-125" style={{ filter: 'blur(var(--glow-blur))' }} />
                <div className="absolute bottom-[5%] right-[5%] w-[45%] h-[45%] rounded-full bg-purple-500/40 animate-lava [--drift-name:drift-wide] [--drift-duration:15s] [--morph-name:morph-alt] [--morph-duration:13s] [--color-duration:22s] [--drift-delay:1s] [--color-delay:2s] [--glow-blur:75px] scale-110" style={{ filter: 'blur(var(--glow-blur))' }} />
                <div className="absolute top-[25%] right-[5%] w-[40%] h-[40%] rounded-full bg-rose-500/40 animate-lava [--drift-name:drift-wide] [--drift-duration:14s] [--morph-name:morph] [--morph-duration:16s] [--color-duration:20s] [--drift-delay:2s] [--color-delay:4s] [--glow-blur:70px] scale-130" style={{ filter: 'blur(var(--glow-blur))' }} />
                <div className="absolute bottom-[15%] left-[10%] w-[35%] h-[35%] rounded-full bg-emerald-500/35 animate-lava [--drift-name:drift-wide] [--drift-duration:17s] [--morph-name:morph-alt] [--morph-duration:14s] [--color-duration:24s] [--drift-delay:3s] [--color-delay:6s] [--glow-blur:65px] scale-115" style={{ filter: 'blur(var(--glow-blur))' }} />
                <div className="absolute top-[30%] left-[30%] w-[30%] h-[30%] rounded-full bg-white/50 animate-lava [--drift-name:drift-wide] [--drift-duration:14s] [--morph-name:morph] [--morph-duration:18s] [--color-duration:30s] [--drift-delay:4s] [--glow-blur:50px] scale-140" style={{ filter: 'blur(var(--glow-blur))' }} />
              </div>
              <div 
                className="hidden dark:block absolute inset-0 overflow-hidden pointer-events-none"
                style={{
                  maskImage: 'radial-gradient(ellipse at center, black 20%, transparent 80%)',
                  WebkitMaskImage: 'radial-gradient(ellipse at center, black 20%, transparent 80%)'
                }}
              >
                <div className="absolute inset-0 bg-[#121212] transition-colors duration-500" />
                <div className="absolute inset-0 opacity-100">
                  <div className="absolute top-[15%] left-[15%] w-[45%] h-[45%] rounded-full bg-blue-600/50 animate-lava [--drift-name:drift-wide] [--drift-duration:15s] [--morph-name:morph-alt] [--morph-duration:12s] [--color-duration:20s] [--glow-blur:70px] scale-120" style={{ filter: 'blur(var(--glow-blur))' }} />
                  <div className="absolute bottom-[5%] right-[10%] w-[40%] h-[40%] rounded-full bg-purple-600/50 animate-lava [--drift-name:drift-wide] [--drift-duration:18s] [--morph-name:morph] [--morph-duration:15s] [--color-duration:22s] [--drift-delay:2s] [--glow-blur:65px] scale-110" style={{ filter: 'blur(var(--glow-blur))' }} />
                  <div className="absolute top-[20%] right-[15%] w-[35%] h-[35%] rounded-full bg-rose-600/45 animate-lava [--drift-name:drift-wide] [--drift-duration:20s] [--morph-name:morph-alt] [--morph-duration:18s] [--color-duration:25s] [--drift-delay:4s] [--glow-blur:60px] scale-130" style={{ filter: 'blur(var(--glow-blur))' }} />
                  <div className="absolute bottom-[15%] left-[5%] w-[30%] h-[30%] rounded-full bg-emerald-600/40 animate-lava [--drift-name:drift-wide] [--drift-duration:22s] [--morph-name:morph] [--morph-duration:20s] [--color-duration:28s] [--drift-delay:6s] [--glow-blur:55px] scale-115" style={{ filter: 'blur(var(--glow-blur))' }} />
                  <div className="absolute top-[40%] left-[40%] w-[25%] h-[25%] rounded-full bg-black/50 animate-lava [--drift-name:drift-wide] [--drift-duration:16s] [--morph-name:morph-alt] [--morph-duration:14s] [--color-duration:35s] [--drift-delay:5s] [--glow-blur:45px] scale-150" style={{ filter: 'blur(var(--glow-blur))' }} />
                </div>
              </div>
              <div className="absolute inset-0 opacity-[0.04] dark:opacity-[0.02] mix-blend-overlay pointer-events-none z-[5]" 
                   style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")` }} />
            </div>
            <div 
              className="absolute inset-0 rounded-3xl pointer-events-none z-10 bg-[var(--neu-surface)]/10 dark:bg-[var(--neu-surface)]/10 shadow-[inset_16px_16px_40px_rgba(0,0,0,0.1),inset_-16px_-16px_40px_rgba(255,255,255,0.7)] dark:shadow-[inset_16px_16px_40px_rgba(0,0,0,0.65),inset_-16px_-16px_40px_rgba(255,255,255,0.04)]"
            />
            <div 
              className="absolute inset-0 rounded-3xl pointer-events-none z-[15] opacity-0 group-active:opacity-100 transition-opacity duration-0 shadow-[inset_6px_6px_12px_rgba(0,0,0,0.1),inset_-6px_-6px_12px_rgba(255,255,255,0.7)] dark:shadow-[inset_6px_6px_12px_rgba(0,0,0,0.5),inset_-6px_-6px_12px_rgba(255,255,255,0.05)]"
            />
            <div className="absolute inset-4 md:inset-5 z-20 pointer-events-none flex items-center justify-center md:block">
              <ArrowUpRight className="md:hidden absolute top-0 right-0 w-4 h-4 text-zinc-500 dark:text-neutral-500 group-hover:text-zinc-700 dark:group-hover:text-neutral-400 transition-colors" />
              <div className="md:absolute md:bottom-0 md:left-0 text-center md:text-left">
                <span className="text-lg sm:text-xl md:text-base font-semibold text-zinc-900 dark:text-neutral-50 block">
                  All Projects
                </span>
                <span className="hidden md:block text-xs text-zinc-800/70 dark:text-neutral-400/70 group-hover:text-zinc-800/90 dark:group-hover:text-neutral-400/90 transition-colors mt-1">
                  Portfolio · Case Studies
                </span>
              </div>
            </div>
          </Link>

          {/* Social Icons (Row 2: Shorter for squares) */}
          <div className="grid grid-cols-2 gap-x-4 gap-y-4 md:gap-5 aspect-[2.15/1] md:aspect-auto h-auto md:h-24 lg:h-28 order-7 md:order-5">
              <a
                href={socialLinks.linkedin}
                target="_blank"
                rel="me noopener noreferrer"
                aria-label="LinkedIn"
                className="rounded-3xl flex items-center justify-center group active:bg-zinc-100/10 transition-all duration-500 ease-in-out neu-raised neu-raised-accent"
              >
                <svg viewBox="0 0 24 24" className="w-8 h-8 fill-zinc-500 dark:fill-zinc-400 group-hover:fill-zinc-900 dark:group-hover:fill-zinc-100 transition-colors duration-500" xmlns="http://www.w3.org/2000/svg">
                  <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                </svg>
              </a>
              <a
                href={socialLinks.github}
                target="_blank"
                rel="me noopener noreferrer"
                aria-label="GitHub"
                className="rounded-3xl flex items-center justify-center group active:bg-zinc-100/10 transition-all duration-500 ease-in-out neu-raised neu-raised-accent"
              >
                <svg viewBox="0 0 24 24" className="w-8 h-8 fill-zinc-500 dark:fill-zinc-400 group-hover:fill-zinc-900 dark:group-hover:fill-zinc-100 transition-colors duration-500" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                </svg>
              </a>
          </div>

          {/* Resume - Bottom Left Alignment (Row 2) */}
          <a
            href={socialLinks.resume}
            download={socialLinks.resumeDownloadName}
            className="group relative rounded-3xl overflow-hidden aspect-[2.15/1] md:aspect-auto h-auto md:h-24 lg:h-28 order-5 md:order-6 flex flex-col justify-end p-4 md:p-5 transition-all duration-500 ease-in-out neu-raised neu-raised-accent"
          >
             <span className="text-sm sm:text-base font-semibold text-zinc-900 dark:text-zinc-50 block">Resume</span>
          </a>

          {/* Contact - Bottom Left Alignment (Row 2) */}
          <a
            href="#contact"
            className="group relative rounded-3xl overflow-hidden aspect-[2.15/1] md:aspect-auto h-auto md:h-24 lg:h-28 order-6 md:order-7 flex flex-col justify-end p-4 md:p-5 transition-all duration-500 ease-in-out neu-raised neu-raised-accent"
          >
             <span className="text-sm sm:text-base font-semibold text-zinc-900 dark:text-zinc-50 block">Contact</span>
          </a>
        </div>
      </div>

      {/* Scroll down indicator */}
      <div className="w-full flex flex-col items-center justify-center mb-0 pb-0 sm:pb-0 sm:mb-0 md:mb-0 md:pb-0 mt-2 md:mt-8 relative z-40">
        <div className={cn(
            "mt-4 md:mt-2 pb-0 md:pb-0 flex justify-center transition-opacity duration-300 lg:opacity-40 lg:hover:opacity-100",
            scrolledDown ? "opacity-0 pointer-events-none" : "opacity-70"
        )}>
          <ChevronDown className="w-6 h-6 text-muted-foreground animate-bounce" />
        </div>
      </div>
    </section>
  )
}

// components/home/HeroSection.vue
<template>
  <section class="relative overflow-hidden bg-black hero-section flex flex-col items-center justify-center min-h-screen">
    <!-- Top area with title and paragraph - keeping original positioning -->
    <div class="mx-auto max-w-7xl px-4 pt-12 pb-2 sm:pb-4 lg:px-8 w-full">
      <div class="text-center hero-content w-full flex items-center justify-center flex-col">
        <div class="inline-block hero-title-wrapper w-full">
          <h1 class="font-bold tracking-tight text-white text-center max-w-full leading-none w-full">
            <!-- Mobile-first hero title with controlled line breaks and smooth size scaling -->
            <span class="hero-title-container inline-block text-center w-full">
              <span class="hero-title-line hero-line-1 block mx-auto text-8xl md:text-6xl lg:text-7xl tracking-tight" style="font-size: 30px !important; line-height: 1.0;">Web &amp; Mobile</span>
              <span class="hero-title-line hero-line-2 block mx-auto text-8xl md:text-6xl lg:text-7xl tracking-tight" style="font-size: 30px !important; line-height: 1.0;">Designer / Developer</span>
            </span>
          </h1>
          <p class="mt-5 sm:mt-8 text-sm sm:text-base md:text-lg leading-6 xs:leading-7 sm:leading-7 text-gray-300 w-[95%] max-w-md sm:w-auto sm:max-w-2xl hero-text font-medium px-2 sm:px-0">
            Mobile apps, web development, and design. Consistent, hands-on, and always evolving.
          </p>
        </div>
      </div>
    </div>
        
    
    
    <!-- Social Links -->
    <div class="flex items-center justify-center space-x-8 mb-4 mt-6">
      <!-- LinkedIn -->
      <a 
        :href="socialLinks.linkedin" 
        target="_blank" 
        rel="noopener noreferrer"
        aria-label="Visit Arjun's LinkedIn profile"
        title="LinkedIn"
        class="h-12 w-12 md:h-16 md:w-16 rounded-md bg-gray-800/80 border border-gray-700/50 flex items-center justify-center shadow-sm hover:bg-gray-700/80 transition-colors group"
      >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-6 h-6 md:w-8 md:h-8 fill-gray-300 group-hover:fill-white transition-colors">
          <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
        </svg>
      </a>
      
      <!-- GitHub -->
      <a 
        :href="socialLinks.github" 
        target="_blank" 
        rel="noopener noreferrer"
        aria-label="Visit Arjun's GitHub profile"
        title="GitHub"
        class="h-12 w-12 md:h-16 md:w-16 rounded-md bg-gray-800/80 border border-gray-700/50 flex items-center justify-center shadow-sm hover:bg-gray-700/80 transition-colors group"
      >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-6 h-6 md:w-8 md:h-8 fill-gray-300 group-hover:fill-white transition-colors">
          <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
        </svg>
      </a>
    </div>
    
    <!-- Bottom area with buttons and scroll arrow - with adaptive margins for different devices -->
    <div class="w-full flex flex-col items-center justify-center mb-0 pb-4 sm:pb-4 sm:mb-4 md:mb-6 mt-4 relative z-40">
      <!-- Buttons -->
      <div class="flex items-center justify-center gap-x-6">
        <a
          :href="socialLinks.resume"
          class="resume-btn rounded-md px-3.5 py-2.5 text-sm font-semibold shadow-sm transition-colors"
          aria-label="Download Arjun's resume as PDF"
          title="Download Resume"
          download
        >
          Download Resume
        </a>
        <a href="#contact" class="text-sm font-semibold leading-6 text-gray-300" aria-label="Jump to contact section" title="Contact Me">
          Contact Me <span aria-hidden="true">→</span>
        </a>
      </div>
      
      <!-- Scroll down indicator - moved up on mobile -->
      <div class="scroll-indicator mt-2 sm:mt-4 pb-4 flex justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-6 h-6 fill-gray-400 animate-bounce-subtle" :class="{'opacity-0': scrolledDown}">
          <path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"/>
        </svg>
      </div>
    </div>

    <!-- Background gradient effect -->
    <div class="absolute inset-x-0 top-0 -z-10 transform-gpu overflow-hidden blur-3xl pointer-events-none">
      <div
        class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-accent to-secondary opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
        style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"
      />
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
const { socialLinks } = useSiteData()

// Reactive state for scroll indicator visibility
const scrolledDown = ref(false);

// Handle scroll events to show/hide the indicator
onMounted(() => {
  window.addEventListener('scroll', handleScroll);
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});

function handleScroll() {
  // Show indicator only when near top of page (e.g., less than 100px scrolled)
  scrolledDown.value = window.scrollY > 100;
}
</script>

<style scoped>
/* Mobile-optimized hero text with balanced lines */
@media (max-width: 640px) {
  .hero-text {
    text-align-last: center;
    hyphens: auto;
    -webkit-hyphens: auto;
    word-spacing: -0.05em;
    line-height: 1.8;
  }
  
  /* Ensure buttons are visible and properly spaced on mobile */
  .resume-btn {
    background-color: var(--color-primary) !important;
    color: var(--color-primary-content) !important;
    border: 1px solid var(--color-primary) !important;
    padding: 0.75rem 1.5rem !important;
    font-size: 0.875rem !important;
    font-weight: 600 !important;
    border-radius: 0.375rem !important;
    text-decoration: none !important;
    display: inline-block !important;
    transition: all 0.2s ease !important;
  }
  
  .resume-btn:hover {
    background-color: transparent !important;
    color: var(--color-primary) !important;
    border-color: var(--color-primary) !important;
  }
  
  /* Ensure scroll indicator is visible on mobile */
  .scroll-indicator svg {
    fill: #9ca3af !important; /* gray-400 */
    opacity: 0.8 !important;
  }
  
  /* Ensure proper spacing for button container on mobile */
  .flex.items-center.justify-center.gap-x-6 {
    gap: 1.5rem !important;
    flex-wrap: wrap !important;
    justify-content: center !important;
  }
}

/* Ensure hero text stays at three lines consistently across all screen sizes */
@media (min-width: 768px) {
  .hero-text {
    max-width: none; /* Allow natural expansion */
    min-width: 42rem; /* Minimum width to ensure 2 lines on larger screens */
    white-space: normal;
    line-height: 1.7;
  }
}

/* Animated gradient text effect for the second hero line */
.hero-line-2 {
  background: linear-gradient(
    90deg,
    #6366f1,
    #8b5cf6,
    #a855f7,
    #d946ef,
    #e879f9,
    #c084fc,
    #6366f1
  );
  background-size: 200% auto;
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  animation: gradient-text 8s linear infinite;
  display: inline-block;
  font-weight: 700;
  text-shadow: 0 0 1px rgba(0, 0, 0, 0.05);
  position: relative;
  transition: filter 0.3s ease;
  padding-bottom: 0.1em;
}

/* Hover effect to make gradient more vibrant */
.hero-line-2:hover {
  filter: brightness(1.1) saturate(1.05);
  animation: gradient-text 4s linear infinite;
  cursor: default;
}

/* Smooth gradient animation */
@keyframes gradient-text {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}

/* Ensure gradient works well in light theme */
.light-theme .hero-line-2 {
  background: linear-gradient(
    90deg,
    #4f46e5,
    #7c3aed,
    #9333ea,
    #c026d3,
    #a21caf,
    #8b5cf6,
    #4f46e5
  );
  background-size: 200% auto;
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  text-shadow: 0 0 1px rgba(0, 0, 0, 0.1);
  animation: gradient-text 8s linear infinite;
  filter: blur(0.2px);
}

/* Ensure dark theme gradient remains unchanged */
.dark-theme .hero-line-2 {
  background: linear-gradient(
    90deg,
    #6366f1,
    #8b5cf6,
    #a855f7,
    #d946ef,
    #e879f9,
    #c084fc,
    #6366f1
  );
  background-size: 200% auto;
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  text-shadow: 0 0 1px rgba(0, 0, 0, 0.05);
  animation: gradient-text 8s linear infinite;
  filter: blur(0.2px);
}

/* Subtle bounce animation for scroll indicator */
@keyframes bounce-subtle {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(4px);
  }
}

.animate-bounce-subtle {
  animation: bounce-subtle 2s ease-in-out infinite;
}

/* Scroll indicator styling */
.scroll-indicator {
  opacity: 0.7;
  transition: opacity 0.3s ease, transform 0.4s ease;
}

.scroll-indicator:hover {
  opacity: 1;
}

.scroll-indicator svg {
  transition: opacity 0.5s ease, transform 0.5s ease;
}

.scroll-indicator svg.opacity-0 {
  opacity: 0;
  transform: translateY(10px);
  pointer-events: none;
}

/* Hide scroll indicator on larger screens where it's less needed */
@media (min-width: 1280px) {
  .scroll-indicator {
    opacity: 0.4;
  }
}
</style>
