// components/home/ContactSection.vue
<template>
  <section id="contact" class="relative py-16 bg-black">
    <!-- Sticky header -->
    <div class="sticky z-30 bg-black/80 backdrop-blur-md py-2" style="top: calc(var(--navbar-height) - 1px);">
      <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <h2 class="text-2xl font-bold text-white">Contact</h2>
      </div>
    </div>
    
    <!-- Contact content -->
    <div class="mx-auto max-w-7xl px-6 pt-10 lg:px-8">
      <div class="max-w-2xl mx-auto text-center mb-12">
        <h3 class="text-xl font-semibold text-white mb-4">Get In Touch</h3>
        <p class="text-gray-300">
          I'm currently open to new opportunities and collaborations. Whether you have a question, 
          a project in mind, or just want to say hello, feel free to reach out!
        </p>
      </div>
      
      <div class="max-w-xl mx-auto">
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <div>
            <label for="name" class="block text-sm font-medium text-gray-300 mb-1">Name</label>
            <input 
              v-model="form.name"
              type="text" 
              name="name"
              id="name" 
              class="block w-full rounded-md border-0 bg-gray-900/50 text-white shadow-sm px-4 py-2.5 focus:ring-2 focus:ring-primary"
              placeholder="Your name"
              required
              :disabled="isLoading || isSuccess"
            />
          </div>
          
          <div>
            <label for="email" class="block text-sm font-medium text-gray-300 mb-1">Email</label>
            <input 
              v-model="form.email"
              type="email" 
              name="email"
              id="email" 
              class="block w-full rounded-md border-0 bg-gray-900/50 text-white shadow-sm px-4 py-2.5 focus:ring-2 focus:ring-primary"
              placeholder="your.email@example.com"
              required
              :disabled="isLoading || isSuccess"
            />
          </div>
          
          <div>
            <label for="message" class="block text-sm font-medium text-gray-300 mb-1">Message</label>
            <textarea 
              v-model="form.message"
              name="message"
              id="message" 
              rows="4" 
              class="block w-full rounded-md border-0 bg-gray-900/50 text-white shadow-sm px-4 py-2.5 focus:ring-2 focus:ring-primary"
              placeholder="Your message here..."
              required
              :disabled="isLoading || isSuccess"
            ></textarea>
          </div>
          
          <div>
            <button 
              type="submit" 
              class="w-full rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-content shadow-sm hover:bg-primary/90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary transition-all duration-300 flex items-center justify-center min-h-[44px]"
              :disabled="isLoading || isSuccess"
              :class="{ 'bg-green-600 hover:bg-green-700 text-white': isSuccess, 'opacity-80 cursor-not-allowed': isLoading }"
            >
              <!-- Loading Spinner -->
              <svg v-if="isLoading" class="animate-spin -ml-1 mr-3 h-5 w-5 text-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              
              <!-- Success Icon -->
              <svg v-else-if="isSuccess" class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
              </svg>
              
              <!-- Button Text -->
              <span>{{ buttonText }}</span>
            </button>
            <p v-if="errorMessage" class="mt-2 text-sm text-red-500 text-center">{{ errorMessage }}</p>
          </div>
        </form>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed } from 'vue'

const form = ref({
  name: '',
  email: '',
  message: ''
})

const isLoading = ref(false)
const isSuccess = ref(false)
const errorMessage = ref('')

const buttonText = computed(() => {
  if (isLoading.value) return 'Sending...'
  if (isSuccess.value) return 'Message Sent!'
  return 'Send Message'
})

const handleSubmit = async () => {
  isLoading.value = true
  errorMessage.value = ''
  
  try {
    const response = await fetch('https://formsubmit.co/ajax/contact@arjunbishnoi.com', {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        name: form.value.name,
        email: form.value.email,
        message: form.value.message,
        _subject: 'New Portfolio Contact',
        _captcha: 'false'
      })
    })
    
    const data = await response.json()
    
    if (response.ok) {
      isSuccess.value = true
      form.value = { name: '', email: '', message: '' }
      
      // Reset button state after 3 seconds
      setTimeout(() => {
        isSuccess.value = false
      }, 3000)
    } else {
      throw new Error(data.message || 'Failed to send message')
    }
  } catch (error) {
    console.error('Submission error:', error)
    errorMessage.value = 'Something went wrong. Please try again later.'
  } finally {
    isLoading.value = false
  }
}
</script>

// src/components/home/ContactSection.tsx
"use client"

import { useState } from "react"
import Image from "next/image"
import { Loader2, Check, Download, Mail } from "lucide-react"
import { cn } from "@/lib/utils"
import { socialLinks } from "@/lib/site-data"

// import { useStickyObserver } from "@/hooks/use-sticky-observer"

export function ContactSection() {
  // const sectionRef = useStickyObserver('Contact')
  const sectionRef = null; // Placeholder
  const [form, setForm] = useState({
    name: "",
    email: "",
    message: ""
  })
  
  const [isLoading, setIsLoading] = useState(false)
  const [isSuccess, setIsSuccess] = useState(false)
  const [errorMessage, setErrorMessage] = useState("")

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    setErrorMessage("")
    
    try {
      const response = await fetch('https://formsubmit.co/ajax/contact@arjunbishnoi.com', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify({
          name: form.name,
          email: form.email,
          message: form.message,
          _subject: 'New Portfolio Contact',
          _captcha: 'false'
        })
      })
      
      const data = await response.json()
      
      if (response.ok) {
        setIsSuccess(true)
        setForm({ name: '', email: '', message: '' })
        
        // Reset button state after 3 seconds
        setTimeout(() => {
          setIsSuccess(false)
        }, 3000)
      } else {
        throw new Error(data.message || 'Failed to send message')
      }
    } catch (error) {
      console.error('Submission error:', error)
      setErrorMessage('Something went wrong. Please try again later.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <section id="contact" ref={sectionRef} className="relative py-10 z-40 bg-background">
      {/* Static Header */}
      <div className="mx-auto max-w-7xl px-6 lg:px-8 pb-2 sm:pb-4">
        <h2 className="text-[1.625rem] md:text-3xl lg:text-4xl text-black dark:text-white font-bold">Contact</h2>
      </div>
      
      {/* Contact content */}
      <div className="mx-auto max-w-7xl px-6 pt-6 sm:pt-8 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-8 xl:gap-16 items-start">
          
          {/* Left Column: Text & Socials */}
          <div className="flex flex-col text-left sm:text-center lg:text-left h-full">
            <p className="text-xl md:text-2xl text-foreground mb-8">
              I&apos;m currently open to new opportunities and collaborations. Whether you have a question, 
              a project in mind, or just want to say hello, feel free to reach out!
            </p>

            {/* Social & Direct Contact Links */}
            <div className="flex flex-col sm:flex-row justify-center lg:justify-start items-center gap-3 md:gap-4 mt-auto w-full">
              {/* Top row on mobile: Social + Resume */}
              <div className="flex gap-3 md:gap-4 w-full sm:w-auto">
                <a
                  href={socialLinks.github}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-center aspect-square h-[3.25rem] sm:h-14 md:h-[3.75rem] rounded-2xl neu-raised group/icon transition-all shrink-0"
                  aria-label="GitHub Profile"
                >
                  <Image src="/github-mark.png" alt="GitHub" width={28} height={28} className="w-6 h-6 sm:w-7 sm:h-7 object-contain filter brightness-0 dark:invert opacity-70 group-hover/icon:opacity-100 transition-all" />
                </a>
                <a
                  href={socialLinks.linkedin}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-center aspect-square h-[3.25rem] sm:h-14 md:h-[3.75rem] rounded-2xl neu-raised group/icon transition-all shrink-0"
                  aria-label="LinkedIn Profile"
                >
                  <Image src="/linkedin-mark.png" alt="LinkedIn" width={28} height={28} className="w-6 h-6 sm:w-7 sm:h-7 object-contain filter brightness-0 dark:invert opacity-70 group-hover/icon:opacity-100 transition-all" />
                </a>

                <a
                  href={socialLinks.resume}
                  download={socialLinks.resumeDownloadName}
                  className="flex flex-1 sm:flex-auto items-center justify-center gap-2 px-6 h-[3.25rem] sm:h-14 md:h-[3.75rem] rounded-2xl neu-raised text-foreground transition-all font-medium text-base sm:text-lg whitespace-nowrap group/icon"
                >
                  <Download className="w-5 h-5 sm:w-6 sm:h-6 opacity-70 group-hover/icon:opacity-100 transition-all" />
                  <span>Resume</span>
                </a>
              </div>

              {/* Bottom row on mobile: Email */}
              <a
                href={socialLinks.email}
                className="flex w-full sm:w-auto items-center justify-center gap-2 px-6 h-[3.25rem] sm:h-14 md:h-[3.75rem] rounded-2xl neu-raised text-foreground transition-all font-medium text-base sm:text-lg whitespace-nowrap group/icon"
              >
                <Mail className="w-5 h-5 sm:w-6 sm:h-6 opacity-70 group-hover/icon:opacity-100 transition-all" />
                <span>contact@arjunbishnoi.com</span>
              </a>
            </div>
          </div>
          
          {/* Right Column: Form */}
          <div className="w-full pt-10 lg:pt-0 lg:pl-8 xl:pl-12">
          <form onSubmit={handleSubmit} className="space-y-5">
            <div>
              <label htmlFor="name" className="block text-base font-medium text-foreground mb-1.5 ml-1">Name</label>
              <input 
                value={form.name}
                onChange={(e) => setForm({...form, name: e.target.value})}
                type="text" 
                name="name"
                id="name" 
                className="block w-full rounded-2xl bg-gray-50/60 dark:bg-white/5 backdrop-blur-sm text-foreground shadow-sm px-5 py-3.5 focus:border-black dark:focus:border-white focus:ring-1 focus:ring-black dark:focus:ring-white placeholder:text-muted-foreground/50 transition-all outline-none"
                placeholder="Your name"
                required
                disabled={isLoading || isSuccess}
              />
            </div>
            
            <div>
              <label htmlFor="email" className="block text-base font-medium text-foreground mb-1.5 ml-1">Email</label>
              <input 
                value={form.email}
                onChange={(e) => setForm({...form, email: e.target.value})}
                type="email" 
                name="email"
                id="email" 
                className="block w-full rounded-2xl bg-gray-50/60 dark:bg-white/5 backdrop-blur-sm text-foreground shadow-sm px-5 py-3.5 focus:border-black dark:focus:border-white focus:ring-1 focus:ring-black dark:focus:ring-white placeholder:text-muted-foreground/50 transition-all outline-none"
                placeholder="your.email@example.com"
                required
                disabled={isLoading || isSuccess}
              />
            </div>
            
            <div>
              <label htmlFor="message" className="block text-base font-medium text-foreground mb-1.5 ml-1">Message</label>
              <textarea 
                value={form.message}
                onChange={(e) => setForm({...form, message: e.target.value})}
                name="message"
                id="message" 
                rows={4} 
                className="block w-full rounded-2xl bg-gray-50/60 dark:bg-white/5 backdrop-blur-sm text-foreground shadow-sm px-5 py-3.5 focus:border-black dark:focus:border-white focus:ring-1 focus:ring-black dark:focus:ring-white placeholder:text-muted-foreground/50 transition-all outline-none resize-y"
                placeholder="Your message here..."
                required
                disabled={isLoading || isSuccess}
              />
            </div>
            
            <div className="pt-2">
              <button 
                type="submit" 
                className={cn(
                  "w-full rounded-2xl bg-black dark:bg-white px-5 py-4 text-base font-bold text-white dark:text-black shadow-sm hover:bg-black/90 dark:hover:bg-white/90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black dark:focus-visible:outline-white transition-all duration-300 flex items-center justify-center min-h-[3.5rem]",
                  isSuccess && "bg-green-600 dark:bg-green-500 hover:bg-green-700 dark:hover:bg-green-600 text-white dark:text-black",
                  isLoading && "opacity-80 cursor-not-allowed"
                )}
                disabled={isLoading || isSuccess}
              >
                {/* Loading Spinner */}
                {isLoading && <Loader2 className="animate-spin -ml-1 mr-3 h-5 w-5" />}
                
                {/* Success Icon */}
                {isSuccess && <Check className="-ml-1 mr-2 h-5 w-5" />}
                
                {/* Button Text */}
                <span>
                    {isLoading ? 'Sending...' : isSuccess ? 'Message Sent!' : 'Send Message'}
                </span>
              </button>
              {errorMessage && <p className="mt-2 text-sm text-red-500 text-center">{errorMessage}</p>}
            </div>
          </form>
        </div>
        </div>
      </div>
    </section>
  )
}
